### ISSUE TITLE
what?

### ISSUE THREAD

**Issue by FreskaQ** [trinhpham/xiaomi-r3g-openwrt-builder#3]
[   74.597946] mtk_soc_eth 1e100000.ethernet eth0: port 3 link up
[   79.786171] mtk_soc_eth 1e100000.ethernet eth0: port 3 link down
[   83.675958] mtk_soc_eth 1e100000.ethernet eth0: port 3 link up
[  103.118782] mtk_soc_eth 1e100000.ethernet eth0: port 3 link down
[  107.090645] mtk_soc_eth 1e100000.ethernet eth0: port 3 link up
[  237.439225] mtk_soc_eth 1e100000.ethernet eth0: port 3 link down
[  240.772956] mtk_soc_eth 1e100000.ethernet eth0: port 3 link up
[  356.561282] mtk_soc_eth 1e100000.ethernet eth0: port 2 link down
[  360.673883] mtk_soc_eth 1e100000.ethernet eth0: port 2 link up

**Comment by trinhpham** [comment]
@FreskaQ, 
This is just an automated build for me to have the latest firmware.
I don't maintain the source code of OpenWrt. If you have issue with the it, please raise it on OpenWrt's forum.
Thanks

PS: The log might be useless as it has no situation, configuration and detail problem followed. You should consider to add more when posting to the forum.
