### ISSUE TITLE
Build failing

### ISSUE THREAD

**Issue by CaioPlazas** [trinhpham/xiaomi-r3g-openwrt-builder#5]
Hey, just a heads-up, the building process is failing. It's been like that for a couple of months now.

Seems like a problem configuring Samba.

**Comment by trinhpham** [comment]
Thank @oiac320 
My apologize that I have no much time to aware on this now. Hope that I could fix it in the middle of Jul (I can't make any promise right now).
If you are able to help, PRs are alway welcome :)

**Comment by trinhpham** [comment]
The build is passed again @oiac320 .
I also added the [help wanted](https://github.com/trinhpham/xiaomi-r3g-openwrt-builder#help-wanted) session, feel free to help if you have some free time :)
Cheers.

**Comment by CaioPlazas** [comment]
Sorry for not replying earlier. I wish I could help but this is not really my area of expertise so I would definitely mess something up instead 😄 

Thanks!
