### ISSUE TITLE
openwrt universal fw builder

### ISSUE THREAD

**Issue by bonuzzz** [trinhpham/xiaomi-r3g-openwrt-builder#6]
Hi. I made own build script based on your idea, but it's more universal as supports all models and all versions. I think it wiil help you.
https://gist.github.com/bonuzzz/55bc231115aac047cee717f6788d9099

usage examples:
docker run --name=openwrt-builder --rm -e VERSION=snapshots -e TYPE=ath79 -e SUBTYPE=nand -e MODEL=glinet_gl-ar750s-nor-nand -v /opt/docker/openwrt:/openwrt openwrt-builder

docker run --name=openwrt-builder --rm -e VERSION=19.07.3 -e TYPE=ramips -e SUBTYPE=mt7620 -e MODEL=miwifi-mini -v /opt/docker/openwrt:/openwrt openwrt-builder

It works about half a year already without error.

**Comment by trinhpham** [comment]
Looks great, @bonuzzz 
The only issue is: Travis-CI doesn't support mounting a volume (`-v` argument of docker command) on its free plan.
I'll try to update my repo on on your idea if I have time :)

**Comment by metaspook** [comment]
Can you made one for "Mi Router 3" too ???

**Comment by trinhpham** [comment]
> Can you made one for "Mi Router 3" too ???

Unfortunately, I have no much time for this.
However, you could use the solution from [the first post](https://github.com/trinhpham/xiaomi-r3g-openwrt-builder/issues/6#issue-655155919)

**Comment by trinhpham** [comment]
Hi @bonuzzz 
I've updated this repository base on your idea. This issue should be closed now.
Thanks so much!

Hi @metaspook,
With latest version of this repo, you can add your device easily by adding its configs to `job` section of the `.travis.yml` file.
Have a look at [fork notes](https://github.com/trinhpham/xiaomi-r3g-openwrt-builder#fork-notes) and give it a try.
Feel free to open an issue if you get into trouble.
Regards.
