### ISSUE TITLE
Which file should I use to flash using breed bootloader?

### ISSUE THREAD

**Issue by Drigoo** [trinhpham/xiaomi-r3g-openwrt-builder#7]
Hello, in fact it is just a question, because I would like to know how do I flash using the breed bootloader.
It is possible, if so, which file to upload?
![5S2IEDV](https://user-images.githubusercontent.com/42247528/87248010-74c71d00-c42d-11ea-9f33-95dc5aea74a5.png)

Thank you if you can answer and sorry for the bad English.

**Comment by trinhpham** [comment]
You should read [the guide](https://openwrt.org/toh/xiaomi/mir3g#installation_via_ssh_for_r3g) at OpenWRT page.
Since flashing custom firmware is not very easy for non-techies, it might void your warranty and brick your device.
Please do it carefully with your own risk.
